import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import Link from "next/link";
import LocalSwitcher from "@/components/local-switcher";
import { useTranslations } from "next-intl";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Header = () => {
  const t = useTranslations("Navigation");

  return (
    <>
      <header>
        <nav className="flex items-center justify-between">
          <Link href={"/"}>{t("home")}</Link>
          <LocalSwitcher />
        </nav>
      </header>
    </>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col mx-10 ">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
